### ISSUE TITLE
Django app will be shipped with Conda/Mamba as default Python package manager

### ISSUE THREAD

**Issue by JV-conseil** [ADernild/ucloud#2]
Date: | 21 March 2023
-- | --
Objet: | Fwd: TICKET-1987 Bump to the latest Python version in Django container

> The new release of the Django app will be shipped with [Conda/Mamba](https://docs.conda.io/en/latest/) as default Python package manager and Nginx as reverse proxy server. Therefore, the default Python interpreter will be the one implemented with Conda, which will not be the latest stable Python release.
> 
> If, for whatever reason, you need to use the latest Python features, you should proceed as follows: 
> 
> • Launch the new Django app in interactive mode.
> • Create a Conda/Mamba environment with the latest version of Python, Django, and all app dependencies by specifying the environment prefix in a path located in /work.
> • After creating the environment, close the job and move the environment folder to a suitable location in the UCloud project.
> • Restart the Django app and mount the environment folder inside the container. 
> • You can set up as default environment the one with the latest Python installation using a simple Bash script imported with the optional "Initialization" parameter.
> This workflow will ensure full reproducibility in both development and production. Furthermore, there will be no long startup times due to reinstallation of all packages/dependencies.
> 
> Also note that the app is general enough to run any Python web server (Flask, Dash, Streamlit, FastAPI, Gunicorn, ...). You just deploy the web server on the same port served by Nginx (by default 8000), which you can also change using the optional "Port" parameter in the Django app.
> 
> For this reason, we do not currently plan to create an app to run a Flask server unless we receive high demand for such an application.

## Pros

1. ...

## Cons

1. ...

**Comment by ADernild** [comment]
### Pros

1. Conda environments come with a range of popular machine learning libraries pre-installed. If you are using numpy, pandas, SciKitLearn etc. in a project, they don't need to be installed.
2. Conda can install and manage system level libraries and non python dependencies, possibly making installation of python packages with lots of system dependencies more automatic.
3. Conda has a strong dependency conflict check, ensuring that conflicting packages and system dependencies can't be installed.

### Cons

1. Conda environments come with a range of popular machine learning libraries pre-installed, making it heavier even though these libraries might not be needed.
2. To get the newest (or at least newer) versions of python and python packages a community managed repo (conda forge) needs to be added. 
3. Either we'll have to use pip inside of a conda environment, or all migrate to using conda environments to generate the `.yml` for the conda environment. 
4. Conda has a strong dependency conflict check that might limit installation of certain libraries together, even though it would work in a venv or pyenv.

[Conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html )
[Blog post](https://codesolid.com/conda-vs-pip/#htoc-moving-to-conda)
